"""add bitacora table

Revision ID: 769503967ccc
Revises: b9c9cb908c6c
Create Date: 2025-11-25 20:18:36.792915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '769503967ccc'
down_revision = 'b9c9cb908c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bitacora_entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('author_profile_id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sa.Integer(), nullable=True),
    sa.Column('categoria', sa.Enum('DISCIPLINA', 'APRENDIZAJE', 'EMOCIONAL', 'OTRO', name='bitacoracategoria'), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('visible_para_padres', sa.Boolean(), nullable=True),
    sa.Column('visible_para_alumno', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_profile_id'], ['profile.id'], ),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['lesson_id'], ['lesson.id'], ),
    sa.ForeignKeyConstraint(['student_profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bitacora_entrada')
    # ### end Alembic commands ###
